name: Refinery Builder
description: Builds and prepares artifacts for delivery

inputs:
  artifact:
    description: Name of the artifact to build
    required: true
  os:
    description: Target operating system
    required: true
  arch:
    description: Target architecture
    required: true
  abi:
    description: Target ABI
    required: false
    default: ""
  version:
    description: Version of refinery to use (e.g. 1, 1.2, v1.0.0 or latest)
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Download Refinery Binary
      shell: bash
      run: |
        case "${{ runner.os }}" in
          Linux) R_OS="linux" ;;
          macOS) R_OS="darwin" ;;
          Windows) R_OS="windows" ;;
          *) exit 1 ;;
        esac

        case "${{ runner.arch }}" in
          X64) R_ARCH="amd64" ;;
          ARM64) R_ARCH="arm64" ;;
          *) exit 1 ;;
        esac

        BINARY_NAME="refinery-${R_OS}-${R_ARCH}"
        [ "$R_OS" = "windows" ] && BINARY_NAME="${BINARY_NAME}.exe"

        RELEASES_JSON=$(curl -sL -H "Accept: application/vnd.github+json" https://api.github.com/repos/SirCesarium/refinery/releases)
        V_INPUT="${{ inputs.version }}"

        if [ "$V_INPUT" = "latest" ]; then
          VERSION=$(echo "$RELEASES_JSON" | grep '"tag_name":' | head -n1 | cut -d'"' -f4)
        else
          [[ ! "$V_INPUT" =~ ^v ]] && V_SEARCH="v$V_INPUT" || V_SEARCH="$V_INPUT"
          DOT_COUNT=$(echo "$V_SEARCH" | tr -cd '.' | wc -c)

          if [ "$DOT_COUNT" -lt 2 ]; then
            VERSION=$(echo "$RELEASES_JSON" | cut -d'"' -f4 | grep -E "^${V_SEARCH}(\.|$)" | sort -Vr | head -n1)
            [ -z "$VERSION" ] && VERSION="$V_SEARCH"
          else
            VERSION="$V_SEARCH"
          fi
        fi

        URL="https://github.com/SirCesarium/refinery/releases/download/${VERSION}/${BINARY_NAME}"

        mkdir -p .refinery_bin
        if ! curl -sSLf -o ".refinery_bin/${BINARY_NAME}" "$URL"; then
          echo "::error::Download failed: $URL"
          exit 1
        fi

        chmod +x ".refinery_bin/${BINARY_NAME}"
        if [ "$R_OS" = "windows" ]; then
          mv ".refinery_bin/${BINARY_NAME}" ".refinery_bin/refinery.exe"
        else
          mv ".refinery_bin/${BINARY_NAME}" ".refinery_bin/refinery"
        fi

        echo "$(pwd)/.refinery_bin" >> $GITHUB_PATH

    - name: Clean dist
      shell: bash
      run: rm -rf dist/ && mkdir -p dist/

    - name: Run refinery build
      shell: bash
      run: |
        FLAGS="--artifact ${{ inputs.artifact }} --os ${{ inputs.os }} --arch ${{ inputs.arch }}"
        [ -n "${{ inputs.abi }}" ] && FLAGS="$FLAGS --abi ${{ inputs.abi }}"
        refinery build $FLAGS

    - name: List distribution
      shell: bash
      run: ls -R dist/
