#!/bin/bash
# install-hooks

mkdir -p .git/hooks
cp hooks/pre-commit.sh .git/hooks/pre-commit
chmod +x .git/hooks/pre-commit

echo "Pre-commit hook installed successfully in .git/hooks/pre-commit."
echo "Run 'git commit' to test it."
