refinery_version = "latest"

[project]
name = "refinery"
lang = "go"
author = "SirCesarium"
license = "MIT"

[naming]
binary = "{artifact}-{os}-{arch}{abi}"
package = "{artifact}-{version}-{os}-{arch}{abi}.{ext}"

[build_refinery]
enabled = true

[[pre_build]]
action = "smoke-test"
once = true
with = { refinery_bin = "./refinery-local" }

[[post_build]]
action = "upload-artifacts"
with = { name = "bin-${{ matrix.artifact }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.abi && format('-{0}', matrix.abi) }}", path = "dist" }

[artifacts.refinery]
type = "bin"
source = "./cmd/refinery"
packages = ["tar.gz", "zip"]

[artifacts.refinery.targets.linux]
os = "linux"
archs = ["amd64", "arm64", "386"]

[artifacts.refinery.targets.windows]
os = "windows"
archs = ["amd64", "386"]

[artifacts.refinery.targets.darwin]
os = "darwin"
archs = ["amd64", "arm64"]
