name: 'Upload Artifacts'
description: 'Uploads build artifacts'
inputs:
  name:
    description: 'Artifact name'
    required: true
  path:
    description: 'Path to upload'
    required: false
    default: dist
  compression-level:
    description: 'Compression level'
    required: false
    default: "0"
runs:
  using: "composite"
  steps:
    - name: Upload Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        if-no-files-found: error
        compression-level: ${{ inputs.compression-level }}
        overwrite: false
