name: Quality Gate
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  check:
    name: Quality & Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Sweet Analysis
        run: curl -L https://github.com/SirCesarium/sweet/releases/download/v5.0.0-rc.4/swt_x86_64-unknown-linux-musl -o swt && chmod +x swt && ./swt
      - name: Check Format
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Run Tests
        run: cargo test
