name: Release & Export

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build (${ matrix.bin } - ${ matrix.target })
    runs-on: ${ matrix.os }
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            bin: test-app
            features: ""
            export_libs: false
            package: false
            docker: false
            use_cross: false
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Refinery Build
        uses: sircesarium/refinery-rs@v2.0
        with:
          target: ${ matrix.target }
          binary-name: ${ matrix.bin }
          features: ${ matrix.features }
          export-libs: ${ matrix.export_libs }
          package: ${ matrix.package }
          publish-docker: ${ matrix.docker }
          use-cross: ${ matrix.use_cross }
          github-token: ${ secrets.GITHUB_TOKEN }